spring:
  datasource:
    url: jdbc:mysql://localhost:3306/primer-proyecto
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true